version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "your_root_password"
      MYSQL_DATABASE: "your_database"
      MYSQL_USER: "your_user"
      MYSQL_PASSWORD: "your_password"
    volumes:
      - db-data:/var/lib/mysql
    platform: linux/amd64

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "your_root_password"
    depends_on:
      - db

volumes:
  db-data: